apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"catalog-deployment","namespace":"default"},"spec":{"selector":{"matchLabels":{"app":"catalog"}},"template":{"metadata":{"labels":{"app":"catalog"}},"spec":{"containers":[{"env":[{"name":"MongoDbSettings__Host","value":"mongodb-service"},{"name":"MongoDbSettings__Password","valueFrom":{"secretKeyRef":{"key":"mongodb-password","name":"catalog-secrets"}}}],"image":"zeref761026/catalog:v2","livenessProbe":{"httpGet":{"path":"/health/live","port":80}},"name":"catalog","ports":[{"containerPort":80}],"readinessProbe":{"httpGet":{"path":"/health/ready","port":80}},"resources":{"limits":{"cpu":"500m","memory":"128Mi"}}}]}}}}
  creationTimestamp: "2021-06-24T18:38:09Z"
  generation: 3
  name: catalog-deployment
  namespace: default
  resourceVersion: "37089"
  uid: 16efa6b5-b139-4470-bf46-32687f5acca5
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: catalog
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: catalog
    spec:
      containers:
      - env:
        - name: MongoDbSettings__Host
          value: mongodb-service
        - name: MongoDbSettings__Password
          valueFrom:
            secretKeyRef:
              key: mongodb-password
              name: catalog-secrets
        image: zeref761026/catalog:v2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: catalog
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-06-24T18:38:09Z"
    lastUpdateTime: "2021-06-24T21:32:26Z"
    message: ReplicaSet "catalog-deployment-79fd8ff7d4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-06-26T18:01:23Z"
    lastUpdateTime: "2021-06-26T18:01:23Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
